server:
  port: 8972 # 이 설정없으면 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:6033/encore
    username: todo_user
    password: todo_passwd

mybastis:
  mapper-locations: mappers/*.xml